import mongoose from "mongoose";

const trainschema = new mongoose.Schema({
	name:{
		type:String
	},
	number:{
		type:Number
	},
	seedlevel:[
		{
			position:{
				type:String,
				enum:['front','middle','rear']
			},
			seed:{
				type:Number,
				default:50
			}
		},
		{
			position:'middle',
			seed:80
		},
				{
			position:'rear',
			seed:75
		}
	],
	route:[{
			stationid:{type:mongoose.Schema.Types.ObjectId,
				ref:'stations'
			},
			order:{
				type:Number
			},
			downboards:[
				{
					position:{
						type:String,
						enum:['front','middle','rear']
					},
					count:{
						type:Number,
						default:0
					}
				}
			],
			totalsample_weight:[
				{
					position:{
						type:String,
						enum:['front','middle','rear']
					},
					count:{
						type:Number,
						default:0
					}
				}
			]
			,running_weight:[
				{
					position:{
						type:String,
						enum:['front','middle','rear']
					},
					count:{
						type:Number,
						default:0
					}
				}	
			]
		}],
	coaches:[
			{
				position:{
					type:String,
					enum:['front','middle','rear']
				},
				crowdlevel:{
					type:Number,
					min:0,
					max:100
				},
				totalsampleweight:{
					type:Number,
					default:0
				},
				lastupdated:{
					type:Date,
					default:Date.now
				}
			}
		]
});
trainschema.index({number:1});
trainschema.index({name:1});
trainschema.index({'route.stationid':1});
export default mongoose.model('trains',trainschema);